spring:

  #---- Datasource Setting ----
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5437}/${DB_NAME:story_protocol}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:jcw}